### ISSUE TITLE
Review usage of assert

### ISSUE THREAD

**Issue by lread** [lread/rewrite-cljc-playground#59]
Much thanks to @sogaiu for bringing this up on Slack.

Rewrite-clj (and therefore rewrite-cljc) makes use of `assert`, mostly to validate node creation, and therefore also for general parsing.  The most common assertion is that a node has the expected number of children.

@sogaiu highlighted the following interesting points (which I am paraphrasing, hopefully correctly):

1. the naive use of `assert` can lead to unintented results as described in ["Use of Assertions" by John Regehr](https://blog.regehr.org/archives/1091) from which @sogaiu quoted:
     > if we are writing library code, we must be even more careful to use assertions correctly than if we are writing a standalone application. The only time to assert something in library code is when the code truly cannot continue executing without dire consequences.

    @sogaiu also came across ["Beware of Assertions" by Alexander Yakushev](http://bytopia.org/2016/10/15/beware-of-assertions/)

2. @borkdude effectively disables these `assert`s for some of his projects, for example [here's how he does so for clj-kondo](https://github.com/borkdude/clj-kondo/blob/a2aede1a78fe83fd78c18e7295f96592b47510df/project.clj#L28), mostly for performance.

If we take point 1 to heart, we can argue that rewrite-cljc really shouldn't be making use of `assert`. It should not be deciding that the situation of encountering invalid Clojure is dire for the calling library/application.

Note that I did replace all explicit Exception throws with `ex-info` exceptions for rewrite-cljc, for cross-platform support between clj and cljs - so I do have a precedent for replacing other types of exceptions.  But I am not sure what makes sense moving forward. Some initial ideas:

1. do nothing and document - this preserves backward compatibility
2. replace with explicit throws - this would allow for a catchable Exception but would break behavior compatibility for folks who want to disable checks for performance (or other) reasons.
3. replace with spec - but spec is not normally enabled in production, so backward compatibility behavior would be an opt-in, and depending on how far we go with spec, might more coarser grained that a caller would like?

**Comment by borkdude** [comment]
Please don't replace with explicit throws. 

Also please don't replace with spec, unless the specs are in a different namespace and optional to load.

**Comment by borkdude** [comment]
Elaborating:

The checks in asserts are mostly useful for developers. They should be elidable at compile time for performance.
For the same reason spec checking should be able to turned off in production environments.

It's nice to get some extra checking during development, but you should be able to turn that off when compiling a final artifact. E.g. linters and formatters should get the ultimate performance possible, since they run on every keystroke.

So I would really do nothing at this point, since people are relying on being able to turn asserts off.

**Comment by lread** [comment]
Thanks @borkdude, much appreciated.

Question to self: if asserts are disabled is rewrite-clj able to parse invalid (or less valid) Clojure code? (Note that this is not necessarily a bad thing).

**Comment by borkdude** [comment]
@lread Note that clj-kondo has been running without asserts for its entire lifetime. So far I haven't had any issues. I think the asserts are mostly there for users creating their own nodes. E.g. for debugging clj-kondo hooks code this could be useful feedback, but that's on clj-kondo to fix, since I've decided to turn the asserts off. In the current API there aren't any asserts that people would miss out on, though.

Asserts aren't bad, they are designed exactly for this purpose.

**Comment by lread** [comment]
Very much related is the usage of `:pre` on some functions, [for example](https://github.com/lread/rewrite-cljc-playground/blob/22ec6e6bf33b70701bd134895b660d1b63231f16/src/rewrite_cljc/node/whitespace.cljc#L85), which are effectively assertions.
Not suggesting we do anything, just taking notes.

**Comment by sogaiu** [comment]
Ah, I didn't realize that about `:pre` -- thanks for sharing!

**Comment by lread** [comment]
Effectively transferred to rewrite-clj https://github.com/clj-commons/rewrite-clj/issues/95
